const movies = [
  {
    name: '33 слова о дизайне',
    link: 'https://www.yakzrobyty.com/media/k2/items/cache/27ea78f3fd31ab764b5ac8ec707175fc_L.jpg',
    likes: ['1'],
    duration: '1ч 42м',
    cardOwner: '1',
  },
  {
    name: 'Киноальманах «100 лет дизайна»',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'В погоне за Бенкси',
    link: 'https://www.yakzrobyty.com/media/k2/items/cache/27ea78f3fd31ab764b5ac8ec707175fc_L.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '1',
  },
  {
    name: 'Баския: Взрыв реальности',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Бег это свобода',
    link: 'https://www.yakzrobyty.com/media/k2/items/cache/27ea78f3fd31ab764b5ac8ec707175fc_L.jpg',
    likes: ['1'],
    duration: '1ч 42м',
    cardOwner: '1',
  },
  {
    name: 'Книготорговцы',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: ['2'],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Когда я думаю о Германии ночью',
    link: 'https://www.yakzrobyty.com/media/k2/items/cache/27ea78f3fd31ab764b5ac8ec707175fc_L.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '1',
  },
  {
    name: 'Gimme Danger: История Игги и The Stooges',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Дженис: Маленькая девочка грустит',
    link: 'https://www.yakzrobyty.com/media/k2/items/cache/27ea78f3fd31ab764b5ac8ec707175fc_L.jpg',
    likes: ['1'],
    duration: '1ч 42м',
    cardOwner: '1',
  },
  {
    name: 'Соберись перед прыжком',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Пи Джей Харви: A dog called money',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'По волнам: Искусство звука в кино',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Рудбой',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Скейт — кухня',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Война искусств',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: [],
    duration: '1ч 42м',
    cardOwner: '2',
  },
  {
    name: 'Зона',
    link: 'https://img.thinkfirsttahoe.org/img/imag-2020/3367/kunitsi-754EC7D.jpg',
    likes: ['2'],
    duration: '1ч 42м',
    cardOwner: '2',
  },
];

export default movies;
